name: Release Build

on:
  release:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build release binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Create release archive
        run: |
          binary_name="env-verify"
          target="${{ matrix.target }}"
          archive_name="${binary_name}-${target}"
          
          mkdir -p dist
          
          # Handle Windows .exe extension
          if [[ "$target" == *"windows"* ]]; then
            cp "target/${target}/release/${binary_name}.exe" "${archive_name}.exe"
            zip "${archive_name}.zip" "${archive_name}.exe"
          else
            cp "target/${target}/release/${binary_name}" "${archive_name}"
            zip "${archive_name}.zip" "${archive_name}"
          fi
          
          echo "ARCHIVE_NAME=${archive_name}.zip" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/zip